### ISSUE TITLE
Quickstart in new VPC fails creating WAPADFSStack

### ISSUE THREAD

**Issue by jhole89** [aws-quickstart/quickstart-microsoft-wapadfs#3]
Hi,

I've been trying to follow the docs for setting up ADFS using the quickstart in a new VPC: https://docs.aws.amazon.com/quickstart/latest/wap-adfs/welcome.html 

This repeatedly fails creating the embedded stack WAPADFSStack with an error of:
```
Embedded stack arn:aws:cloudformation:eu-west-2:stack/WAP-ADFS-WAPADFSStack-1UM41VJDR9RLN/acd242f0-ad5f-11e9-a1e2-0ab69c38e076 was not successfully created: The following resource(s) failed to create: [WAP1EIP, WAP1WaitCondition, ADFS2WaitCondition, WAP2WaitCondition]. 
``` 
Any suggestions?

**Comment by davmayd** [comment]
This Quick Start has been refactored and the issue has been resolved
