### ISSUE TITLE
Deploy WAP and AD FS into new VPC, FQDN options limited to .com

### ISSUE THREAD

**Issue by BrandenNaidoo** [aws-quickstart/quickstart-microsoft-wapadfs#32]
Section heading: Deployment options
Documentation issue description: Deploy WAP and AD FS into new VPC, FQDN options limited to .com tld's as apposed to deploying into an existing VPC, please add domain.co.za as an option - this worked during November last year. Now we only allowed domain.com to be inserted into the stack option for Domain DNS name's.
 
Error :

"CREATE_FAILED | Parameter 'DomainDNSName' must match pattern ^[a-zA-Z0-9]+[a-zA-Z0-9\-]*\.[a-zA-Z0-9]+$"

**Comment by davmayd** [comment]
The issue is actually with a submodule (https://github.com/aws-quickstart/quickstart-microsoft-activedirectory), which had its RegEx updated three weeks ago. I'm rolling back the changes now.

**Comment by BrandenNaidoo** [comment]
Thanks!
